config/routes.rb
Rails.application.routes.draw do #Railsアプリケーションのルーティング設定を開始
  
  root 'game#index' 
  #アプリケーションのルートURL（"/"）にアクセスしたとき、GameControllerのindexアクションを呼び出します。
  post 'game/check_answer',to:'game#check_answer', as: 'check_answer'
  #/check_answerというURLにPOSTリクエストを送る
  #GameControllerのcheck_answerアクションが呼び出される
  post 'game/reset', to: 'game#reset' , as: 'reset'
  #/check_answerというURLにPOSTリクエストを送ると、
  #GameControllerのcheck_answerアクションが呼び出されます。
  post 'game/new_question', to: 'game#new_question' , as: 'new_question'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  #GameControllerという名前のコントローラクラスを定義
  #ApplicationControllerを継承

  def index
    reset_game
    #reset_gameメソッドを呼び出す
  end

  def check_answer
    @r = params[:r].to_i
    @g = params[:g].to_i
    @b = params[:b].to_i


    @randam_num=generate_new_color()

    
    puts @randam_num
    puts @randam_num[:r]
    puts @randam_num[:g]
    puts @randam_num[:b]
    

    @ran_r=@randam_num[:r]
    @ran_g=@randam_num[:g]
    @ran_b=@randam_num[:b]

    
    @score = calculate_score(@r, @g, @b,@ran_r,@ran_g,@ran_b)#インスタンスを呼び出している
    
    @message = score_message(@score)#インスタンスを呼び出している
    @color = session[:color]#セッションから正解の色 (session[:color])を取得
    @correct_color = session[:color] # 正解の色をビューに渡す
    render :index
  end

  def reset
    #gameをリセットする,リセットボタン
    reset_game
    render :index
  end

  def new_question
    #新しいクイズ
    generate_new_color
    render :index

  end

  private

  def reset_game
    #ゲームをリセットする
    session[:score] = 0
    generate_new_color
  end

  def generate_new_color
    @color = { r: rand(256), g: rand(256), b: rand(256) }
    session[:color] = @color
    #puts @color
  end

  def calculate_score(r, g, b,ran_r,ran_g,ran_b)#RGB値の違いに基づいてスコアを計算する
    correct_color = session[:color]
        if r==ran_r && g==ran_g && b== ran_b then
          puts(r)
          puts(g)
          puts(b)
          puts("正解")
        else
          puts(r)
          puts(g)
          puts(b)
          puts("間違い")  
        end
    #  if correct_color.nil?
    #   generate_new_color
    #   correct_color = session[:color]
    # end
    # score = 0
    # score += point_for_color(r, correct_color[:r])
    # score += point_for_color(g, correct_color[:g])
    # score += point_for_color(b, correct_color[:b])
    # session[:score] += score
    # score
  end

  def point_for_color(guess, correct)
    #スコアに基づいてメッセージを生成する
    return 0 if correct.nil?

    diff = (guess - correct).abs
    case diff
    when 0
      10
    when 1..2
      8
    when 3..6
      6
    when 7..10
      4
    when 11..30
      2
    when 31..50
      1
    else
      0
    end
  end

  def score_message(score)
    if score == 30
      "正解です！"
    else
      "スコア: #{score}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/views/game/check_answer.html.erb
<h1>Game#check_answer</h1>
<p>Find me in app/views/game/check_answer.html.erb</p>
<-- Game#check_answerというメソッドが、app/views/game/check_answer.html.erbというファイルに関連していることを示しています。-->

app/views/game/index.html.erb
<h1>after</h1> 
<div style="width: 100px; height: 100px; background-color: rgb(255,254,250); border: 2px solid black;"></div> 
<h1>この色何色</h1> 
<div style="width: 100px; height: 100px; background-color: rgb(5,24,205);border: 2px solid black;"></div> 

<%= form_with url: check_answer_path, method: :post do %>
  <p>
    <label for="r">R:</label>
    <input type="number" id="r" name="r" value="<%= @r %>" />
  </p>
  <p>
    <label for="g">G:</label>
    <input type="number" id="g" name="g" value="<%= @g %>" />
  </p>
  <p>
    <label for="b">B:</label>
    <input type="number" id="b" name="b" value="<%= @b %>" />
  </p>
  <p>
    <%= submit_tag "回答" %>
  </p>
<% end %>

<p><%= @message %></p>

<% if @r && @g && @b %>
  <p>あなたの回答: R=<%= @r %>, G=<%= @g %>, B=<%= @b %></p>
  <p>正解の色: R=<%= @correct_color[:r] %>, G=<%= @correct_color[:g] %>, B=<%= @correct_color[:b] %></p>
<% end %>



<!--  border: 2px solid black;-->
<!--
</div> 

<h1>色あてゲーム</h1>
<p>画面の色をRGBそれぞれの値で答えてくださいね</p>
<p>これであなたも色彩マスター</p>


<div style="width: 100px; height: 100px; background-color: rgb(<%= @color[:r] %>, <%= @color[:g] %>, <%= @color[:b] %>);"></div> 
<div style="width: 100px; height: 100px; background-color: rgb(255,254,255);"></div> 

<%= form_with url: check_answer_path, method: :post do %>
  <p>
    <label for="r">R:</label>
    <input type="number" id="r" name="r" value="<%= @r %>" />
  </p>
  <p>
    <label for="g">G:</label>
    <input type="number" id="g" name="g" value="<%= @g %>" />
  </p>
  <p>
    <label for="b">B:</label>
    <input type="number" id="b" name="b" value="<%= @b %>" />
  </p>
  <p>
    <%= submit_tag "回答" %>
  </p>
<% end %>

<p><%= @message %></p>

<% if @r && @g && @b %>
  <p>あなたの回答: R=<%= @r %>, G=<%= @g %>, B=<%= @b %></p>
  <p>正解の色: R=<%= @correct_color[:r] %>, G=<%= @correct_color[:g] %>, B=<%= @correct_color[:b] %></p>
<% end %>

-->

app/views/game/new_question.html.erb
<h1>Game#new_question</h1>
<p>Find me in app/views/game/new_question.html.erb</p>

app/views/game/reset.html.erb
<h1>Game#reset</h1>
<p>Find me in app/views/game/reset.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColorGuessingGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>